auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  # path_prefix zostaje lokalny - to tylko WAL/cache instancji, nie chunki/indeks.
  path_prefix: /tmp/loki
  storage:
    azure:
      connection_string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      container_name: loki-chunks
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  retention_period: 24h

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: azure
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /tmp/loki/retention
  delete_request_store: azure
  retention_enabled: true
